### ISSUE TITLE
Code optimization for Bundle size

### ISSUE THREAD

**Issue by adibas03** [OneSignal/react-native-onesignal#1009]
**Description:**

We recently added One signal to our react native App, only to realize that the bundle size is about 22mb, being that our app's size was at 18mb, adding one signal, basically more than doubled the app bundle.
The questions are:
- Are there plans to optimize the code by breaking it up into packages
- Is there a timeline
- How can we participate to achieve this?

**Environment**
OneSignal: ^3.7.3
packager: npm(yarn)
OS: android

**Steps to Reproduce Issue:**
(write below this line) -->

  1. Install the OneSignal SDK using npm into your project
  2. Build application

**Anything else:**

**Comment by rgomezp** [comment]
Howdy,
Great question. The npm package is 22MB because it includes support on the iOS side for non-cocoapods and manual imports. However, note that the final app size shouldn't be affected. To confirm, are you seeing otherwise? If so, it's likely this bulk is coming from somewhere else. Perhaps you can try to remove the package to see if the bundle size is greatly reduced. Cheers

**Comment by adibas03** [comment]
Hey @rgomezp 
As a matter of fact, We observed at least 20MB increase in the production app
Investigated by removing the package and then adding it back, and we were able to confirm OneSignal as the culprit.

**Comment by jkasten2** [comment]
@adibas03 Can you extract your APK to see if there are any extra files after adding OneSignal? Or any files that increased by are large amount, such as a .dex file.

This SDK only depends on `invariant` on the JS side, which is only ~7KB.
https://github.com/OneSignal/react-native-onesignal/blob/3.8.1/package.json#L10

From the native side, the Java part of OneSignal is in the 500KB range:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.14.1/OneSignalSDK.jar

OneSignal also depends on the Google FCM library that will add 1 to 2MB. OneSignal also depends on the Android Support / AndroidX libraries. This may add up to 2MB, but most apps have some or all parts of this from other SDKs.

Lastly a good amount of the above native libraries can be cut down a lot by enabling Proguard / R8 in your project.

Since you are seeing a large 20MB it sounds like something is being added to your APK that shouldn't be so inspecting the file inside should help you find the root cause.

**Comment by adibas03** [comment]
Hey @jkasten2 @rgomezp 
Apologies are in other,
Been doing further investigation and realized, OneSignal is innocent, and only added about 1MB to the bundle size.
You guys are doing an awesome job.
The problem is no fault of OnSignal, though code Optimization is never a bad Idea

**Comment by rgomezp** [comment]
Howdy!
Not a problem. Hopefully this thread helps someone in the future with the same issue.

Enjoy!
