### ISSUE TITLE
ids event invoked twice.

### ISSUE THREAD

**Issue by samslow** [OneSignal/react-native-onesignal#1031]
```js
constructor(props) {
    super(props);
    OneSignal.init(ENV.OnesignalAppKey, {
      kOSSettingsKeyAutoPrompt: true,
      kOSSettingsKeyInFocusDisplayOption: 2,
    });
    OneSignal.inFocusDisplaying(2);
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', (event) =>
      this.onOpened(event, this.props.navigation),
    );
    OneSignal.addEventListener('ids', this.onIds);
  }

  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }

···

  onIds(device) {
    console.log('Device info: ', device);
    AsyncStorage.getItem('token').then((token) => {
      if (token == null) {
        OneSignal.getPermissionSubscriptionState(async (p) => {
          if (p.notificationsEnabled === false) {
            setUserStatus(['generalAlarm', 'alarmStatus'], false);
          }
          const originToken = await AsyncStorage.getItem('token');
          if (originToken === null) {
            const res = await getToken(p.userId);
            const AuthToken = res.data.token;
            await AsyncStorage.setItem('token', AuthToken);
          }
        });
      }
    });
  }
```

I'm using `OneSignal.getPermissionSubscriptionState()` to get appPlayerId.
OneSignal is getting appPlayerId from onIds because it only provides it after 30 seconds when the app first runs.

But the problem is that the onIds function runs twice so This causes the problem of making tokens twice.
Can you solve this? help me please

![image](https://user-images.githubusercontent.com/26738367/89563684-c7420080-d856-11ea-8251-7332b1c58878.png)

**Comment by rgomezp** [comment]
Howdy,
The `ids` event fires automatically when you add it via the `addEventListener` method. This change was implemented [here](https://github.com/OneSignal/react-native-onesignal/pull/765).

Later, we renamed the `configure` method to `idsAvailable` which was implemented [here](https://github.com/OneSignal/react-native-onesignal/pull/827).

It looks like this should only be happening in the iOS implementation. Can you confirm?

This is presumably due to the event also firing on [subscription changes](https://github.com/OneSignal/react-native-onesignal/blob/76299d150d73b95495cd88710709c252a731cb2c/ios/RCTOneSignal/RCTOneSignal.m#L120) in iOS. We will look into this. Thanks for your patience.

**Edit:** (Correction) There are cases were ids can fire twice. If for example the device register with OneSignal without a pushToken, then later gets a token.

**Comment by samslow** [comment]
Good Thanks

I solved the problem with your help. 

I think it's a good thing to know a new method.
