### ISSUE TITLE
groupedNotifications missing from opened handler

### ISSUE THREAD

**Issue by kmkrtich** [OneSignal/react-native-onesignal#1046]
**Description:**
When I'm getting 4 notifications they are automatically being groupped by Android system, so I want to handle click event on the grouped notification item. When I click on that group notification item I dont' get all group items, but instead receive only last notification.

OneSignal.addEventListener('opened', openResult => {
       console.log('THIS IS OPEN RESULT: ', openResult);
});

Documentation says that openResult should be of OSNotificationOpenResult type which has groupedNotifications list, but actually ther is not such properties.

Attached is real of openResult:
![Screenshot from 2020-09-23 12-08-03](https://user-images.githubusercontent.com/48594915/94070909-11ca0d00-fe04-11ea-8467-8e6191821438.png)

**Expected Result**
Somehow identify that clicked notification is not single but group of notification.
Expose group notification items in groupedNotifications property

**Environment**
Platform : Android
React Native : 0.61.5
OneSignal sdk version : 3.9.1
Added by npm

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
1. Initialize the SDK in Android
1. Subscribe for notificatoin open handler
1. Attempt to receive 4 push notifications, so that they will be displayed in a single group
1. Click on the group notification item.

**Comment by animaksy** [comment]
+1

**Comment by rgomezp** [comment]
Howdy,
Thanks for opening this issue. If the `groupedNotifications` is missing from the payload, it means the grouped notifications object was null. On the native side, this key-value pair is only added to the payload if it is non-null.

Take a look [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotification.java#L135-L140).

Since this is a native-side issue, could you please open this same issue in that repository? We can continue tracking it there.

Cheers
