### ISSUE TITLE
[Beta] Badge doesn't seem to decrese

### ISSUE THREAD

**Issue by KDederichs** [OneSignal/react-native-onesignal#1092]
**Description:**

The Badge displayed on the icon doesn't seem to decrease when the app is opened.

**Environment**

RN 0.63.3
rn-onesignal beta 4
iOS 14.2

**Steps to Reproduce Issue:**

1. send notifications that will increase the batch 
1. open the app from the normal home screen

**Anything else:**

I'm using the service extention from your documentation

**Comment by emawby** [comment]
Hello thank you for the report. This is a known issue with the iOS Native SDK that has been fixed and will be available with the next React-Native beta release.

**Comment by rgomezp** [comment]
Howdy,
We have fixed this bug and will be included in the next release. Thank you

**Comment by KDederichs** [comment]
Would you guys maybe consider releasing a new version with this?
Or is it not viable to try to use the beta atm anyways?

**Comment by rgomezp** [comment]
Howdy,
This is currently on the [master branch](https://github.com/OneSignal/OneSignal-iOS-SDK) of the native SDK. We are still waiting to include more fixes before making another release.

That said, if you would like to expedite the process, you can manually update the underlying SDK yourself by following [these instructions](https://documentation.onesignal.com/docs/react-native-sdk-setup#manually-updating-ios-onesignalnativesdk). Note that instead of following step 1, you should download from the master branch. (As of 11/19/20)

Cheers
