### ISSUE TITLE
onIds not responding

### ISSUE THREAD

**Issue by vt978** [OneSignal/react-native-onesignal#1185]
**Description:**

Previously i have set up a test and live version with different one signal account for my app which both were working fine until recently after rebuild.

For the test version, i notice the push token returns null, when i check one signal it showed google play service library error.

So i went to check the live version if it has the same problem but the OneSignal.addEventListener('ids', this.onIds); was no longer responding. I switch back to to test version and it was the same. 

No changes were made since it was working fine until recently it was rebuild. Is this cause of the recent 4.0.0 upgrade ? Do i need to migrate ? 

(your description here)

**Environment**

one signal version : v3.9.2
i've followed the step-by-step installation instruction and it was working fine until recently.

**Steps to Reproduce Issue:**

1. install onesignal sdk following installation guide
1. run project, view log if OneSignal.addEventListener('ids', this.onIds);

sample code : 
 componentDidMount() {
      OneSignal.registerForPushNotifications();

```
  OneSignal.setLogLevel(6, 0);
```

```
 OneSignal.init("xxxxxxxxxxxxx", {kOSSettingsKeyAutoPrompt : false, kOSSettingsKeyInAppLaunchURL: false, kOSSettingsKeyInFocusDisplayOption:2});
        
  OneSignal.inFocusDisplaying(2); 
```

```
  OneSignal.addEventListener('received', this.onReceived);
  OneSignal.addEventListener('opened', this.onOpened);
  OneSignal.addEventListener('ids', this.onIds);
```

}

  onReceived(notification) {
      console.log("Notification received: ", notification);
  }

  onOpened(openResult) {
      console.log('Message: ', openResult.notification.payload.body);
      console.log('Data: ', openResult.notification.payload.additionalData);
      console.log('isActive: ', openResult.notification.isAppInFocus);
      console.log('openResult: ', openResult);
  }

  onIds(device) {
      console.log('Device info: ', device);
  }

**Comment by rgomezp** [comment]
Howdy,
If you're on 3.9.2 the IDS event should work.

However, we _do_ in fact recommend you upgrade to the latest version since it will most likely fix the issue for you. 

Version 4+ of the SDK API is very much improved so I believe it is in everyone's best interest to do so.

Please see the migration guide in our documentation for help migrating from version 3.

Enjoy!

**Comment by vt978** [comment]
i have migrate to newest version 4.0.5 and it seem to be working fine at first. getDevicestate successfully get user id and token but only for first few time when i restart the app. 

Not long after a few restart later, i start to face problem similar to #1191 where getDevicestate sometime does not return user id and token.

**Comment by rgomezp** [comment]
Howdy,
Thank you for your response.

This will be fixed in the upcoming release. However, you should still be practicing best practices by only getting the device state in the observer callback.

See this [comment](https://github.com/OneSignal/react-native-onesignal/issues/1159#issuecomment-811509482) for more info
---
