### ISSUE TITLE
Didn't find class "com.google.firebase.iid.FirebaseInstanceId" 

### ISSUE THREAD

**Issue by tinyCoder32** [OneSignal/react-native-onesignal#1222]
**Description:**
Followed up the setup multiple times making sure everything is done correctly, the user is being added to onesignal's user list with a "No Push Token" error, while it throws the below error in Android Studio:

![image](https://user-images.githubusercontent.com/17817239/118968776-fb655880-b974-11eb-9e2c-96e0a0b392da.png)

I also followed the troubleshooting guide, and found out some outdated documentaion (like the one in onesignal's main home page!):

Example (the init function doesn't exist anymore)

![image](https://user-images.githubusercontent.com/17817239/118968947-2a7bca00-b975-11eb-871d-e370ab9824b8.png)

**Environment**

1. What version of the OneSignal React-Native SDK are you using?
Latest currently (4.1.0)

2. How did you add the SDK to your project (eg. npm)
npm 

**Steps to Reproduce Issue:**
  1. Install OneSignal SDK using npm 
  2. Initialize the SDK for android with `OneSignal.setAppId("XXX")`
  3. User appears on the list with a `No Push Token` error

![image](https://user-images.githubusercontent.com/17817239/118969245-81819f00-b975-11eb-93f1-1bb2009a069e.png)

**Comment by jkasten2** [comment]
@tinyCoder32 Thanks for reporting!

* Android FCM issue - The error you reported is due to a compatibility issue with OneSignal not supporting Fireabase 22 that was released in May. This is now fixed though in [react-native-onesignal 4.1.1](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.1.1)
* Thanks for pointing on the example code on the onesignal.com homepage. This is the older 3.x.x API and will update. The full [documucation.onesignal.com react native setup guide](https://documentation.onesignal.com/docs/react-native-sdk-setup) though is updated.
