### ISSUE TITLE
[Question] Local notifications - Persistent notifications - Reply in notification

### ISSUE THREAD

**Issue by pabloppp** [OneSignal/react-native-onesignal#126]
### Persistent notifications
I'd like to know it there would be a way to make persistent notifications using this API, so for example:
- In Whatsapp, when I receive 2 notifications from 2 different chats they get stacked. If you click on the stacked notification it doesn't get removed from the notification drawer on the phone, but instead the app is opened and I see the list of the chats, highlighting those that have new messages. When I open one of the chats the notifications get cleared, but not before, so if I close the app before entering a chat, I still keep the notification telling me I have new messages.
- In some apps, a notification is shown as long as a specific process is running (music playing, for example). If you click on the notification the app is opened but the notification remains there. If you close the notification the process gets killed (that would maybe need a new event like`onNotificationDismissed` or something similar??)

### Local notifications
I also would like to know if it would be too difficult to send or schedule local notifications: Let's say I want to catch a notification event when the app is open without displaying it with `enableNotificationsWhenActive` set to **false**, then depending on the state of the app or the notification content I want to show the notification (ex: I don't want to show notifications of chat messages if the chat room is open, but I want to get notifications for other chat rooms different than the one I'm in). I tried to solve this using other libraries that handle notifications but there seems to be some incompatibilities with this library.

### Reply in notification
Lastly, in the new Android 7 there is a way to send replies from the notification, sometimes without even unlocking the phone. Probably this should be enabled by the OneSignal API server side and not just in this library, but maybe there is a way??

[ADDED 2017/01/13]
### Group notification in android 7
- If you press on a notification in a group, only that one is cleared, but what if I want to clear ALL the notifications in a group without clearing other 'non-grouped' notifications?
- Group message doesn't seem to work on Android 7, it only shows the notification list but no group message.
Thank you!!!

**Comment by avishayil** [comment]
That's a good questions.
Maybe @jkasten2 will elaborate.

**Comment by pabloppp** [comment]
Thanks for bringing this up @avishayil 
I am going to add another couple questions:

In android 7 the notification grouping works a little bit different, You can expand a grouped notification to show the full list of notifications and you can press on each of them separately, this brings 2 questions:
- If you press on a notification in a group, only that one is cleared, but what if I want to clear ALL the notifications in a group without clearing other 'non-grouped' notifications?
- Group message doesn't seem to work on Android 7, it only shows the notification list but no group message.

**Comment by avishayil** [comment]
I didn't had the chance to check this feature on a real device yet, but i'll try to do so in the next week.
I hope i'll have better answers for you by then.

**Comment by jkasten2** [comment]
@pabloppp @avishayil

#### Persistent notifications
1. I am not sure I fully understand the behavior your looking for here. Right now with OneSignal tapping on a summary notification will remove it from the shade and the summary with all the sub notifications will be passed to the open even where your app can read them.

2. This is an `ongoing` notification however these are used for currently running events. They aren't really designed for pushes.

#### Local notifications
This SDK doesn't have support for local notifications. We will consider this use case of how the notification should be display per notification instead of a preset flag. The OneSignal SDK shouldn't be interfering with other notification SDK. I would try updating to the 2.0 version of this SDK as there has been some updates to fix iOS compatibility issues with other SDKs.

#### Reply in notification
The is currently isn't support for this in the OneSignal Android native SDK yet but will be added in the future.


#### Group notification in android 7
1. Google has made a number of large style changes in Android 7. However tapping on the top level notification should behave like Android 6 and older devices where all grouped notifications are counted as opened. The change however being that the use can now expand the bundle (AKA group) and open or dismiss the individual notifications.

2. The change however is that the summary notification is no longer displayed. The collapsed view of the top level notification is now like the expanded view of pre-7 devices. There is a new `setSubText` method which display after the app name but this is much more limited and even a title may not fit well here. The OneSignal `android_group_message` text also doesn't fit here we are considering just making another field specifically for this sub text.

**Comment by pabloppp** [comment]
> Right now with OneSignal tapping on a summary notification will remove it from the shade

Exactly, I'd like the grouped notification to stay in the notification drawer until I explicitly want to remove it.

--- 

Regarding local notifications, would there be a way to forward notifications when they are received to choose wether to show it or not? For example:
```
onNotificationReceived: function(notification) {
  if(notificationChatIsOpen){
    return false; //this will prevent the notification from showing if the notification belongs to the same chatRoom that is open.
  }
  return true; 
}
```
or alternatively 
```
onNotificationReceived: function(notification, forward) {
  if(!notificationChatIsOpen){
    forward(notification); //this would allow to modifiy the notification object before forwarding it
  }
}
```

**Comment by jkasten2** [comment]
@pabloppp That behavior seems a bit odd, to me. I feel the notification should be dismissed after tapping on it as an action is being performed on it. The full details of the summary notification should then be shown to the user. This is how Gmail behaves for example.

---

Had some of the same ideas in mind. However this first needs to be implemented in the native SDKs. Also fallback support for iOS 9 for example will need to be considered before we pick a API. We want to make any behavior we add as consistent as possible for all devices without the need for the app developer to implement extra edge case events / APIs.

**Comment by pabloppp** [comment]
> This is how Gmail behaves for example  
 
I must disagree on it being the norm, as gmail do not group notifications from different threads, but even if it was the norm, one of the cool things about notifications is how much you can customize them. In Android you can even use an XML layout! So I don't see why I should be forced to close notifications on tap when native notifications do have the option to not do so `notification.flags |= Notification.FLAG_AUTO_CANCEL;`

OneSignal is very awesome because it provides a unified place to send notifications, but is pretty limited on how notifications should behave.

Anyway, thanks for taking time to answer, if you think this is not relevant anymore please do not hesitate on closing the issue.

**Comment by jkasten2** [comment]
True, Gmail groups by account instead of a thread. For a chat app I would recommend setting a different `android_group` to each conversation.

We do have a `NotificationExtenderService` that can be used to fully customize Android notifications. It allows you to fully use anything on the Android `NotificationCompat.Builder` object. However this must be done with native Java code. See our [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) section for more details.

Thanks.

**Comment by pabloppp** [comment]
@jkasten2 thanks, I was hoping for a complete react-native (js) solution, but that will do it for now! 🙇
