### ISSUE TITLE
Background notifications not opening on some android 11 devices

### ISSUE THREAD

**Issue by aaroncornelissen** [OneSignal/react-native-onesignal#1288]
**Description:**

Background notifications are not opening on click on some android 11 devices. The OnesSignal NPM module worked correctly with my phone (Redmi note 8 pro) when my phone was running android 10. After the update to android 11 my phone won't open the app after clicking the onesignal push messages anymore. Previousy the app was starting up after I clicked on the push notification, but now it does nothing.  I've tried everything with the app en energy settings in my mobile, but nothing works. All other apps notification will trigger apps to open. My coworker with an Samsung s10 has the same problem.

On the android 11 Pixel simulator the app will open when I click on the push notification. 

**Environment**

react-native-onesignal: 4.3.0
react-native: 0.64.2
installed with NPM

**Comment by sclavijo93** [comment]
I have the same problem with Android 10 but only the first time. If I touch a second push notification it does open the app.

On iOS works well

react-native: 0.63.3
react-native-onesignal: 4.0.1
android: 10
Phone: Redmi 8A

**Comment by rgomezp** [comment]
Howdy,
So are you sending content along with the background data?

Can you please include your [service extension](https://documentation.onesignal.com/docs/service-extensions) native code?

Cheers

**Comment by aaroncornelissen** [comment]
> Howdy,
> So are you sending content along with the background data?
> 
> Can you please include your [service extension](https://documentation.onesignal.com/docs/service-extensions) native code?
> 
> Cheers

I'm not having a server extension, because I only use visible notifications. 

The push message from the API succesfully arrives at the android device, but if the app is swiped away the app won't open. If I open the app after I clicked on two notifications then I recieve two setNotificationOpenedHandler events.

The app will open on notification click when the app is open in the background.

**Comment by rgomezp** [comment]
I see. Thanks for the info. We will need to try to reproduce. Thanks for your patience.

**Comment by aaroncornelissen** [comment]
> I have the same problem with Android 10 but only the first time. If I touch a second push notification it does open the app.
> 
> On iOS works well
> 
> react-native: 0.63.3 react-native-onesignal: 4.0.1 android: 10 Phone: Redmi 8A

I can relate to that. The app also opens from setNotificationOpenedHandler if the app is open in the background. 

@rgomezp Thanks for looking into this!

**Comment by rgomezp** [comment]
Howdy,
I went ahead and tried reproducing this with 0.64.1 and the SDK 4.3.1 on a Samsung Galaxy S20 with no luck.

It could be an issue with certain devices only. But if the folks seeing the issue could please include a code snippet of their OneSignal related code that would be helpful.

Cheers

**Comment by rgomezp** [comment]
From #1292 : 

> I reverted back to react-native-onesignal@4.1.1 and everything works as expected. The app opens even on kill state for Android, and the deep linking works as expected as well.

> I haven't checked for IOS but I think it will work too because my other app is working fine using 4.1.1.

This is useful thanks for testing @nickksm

**Comment by jkasten2** [comment]
> I have the same problem with Android 10 but only the first time. If I touch a second push notification it does open the app.

@sclavijo93 The exact issue you are describing was fixed in [react-native-onesignal 4.0.4](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.0.4).

**Comment by jkasten2** [comment]
@aaroncornelissen Could you attach a full .log from logcat with VERBOSE logging and no app filters reproducing the issue? 

If you don't want to share this publicly due to any possible sensitive information you can share with OneSignal support and also include a link to this issue when you reach out.

**Comment by FreTimmerman** [comment]
is this possibly related to https://github.com/OneSignal/OneSignal-Android-SDK/issues/1427 ?

i'm also having this issue on RN@0.66.1 with RN-onesignal@4.3.1 on android 8

when app is in background and i press the notification, `setNotificationOpenedHandler` does get called, but the app doesn't open.

when adding to `AndroidManifest.xml`:
```
<meta-data android:name="com.onesignal.suppressLaunchURLs" android:value="true"/>
```
the app does open, but it's not following the deeplink url provided by `launchURL` (obviously, since i told it to suppress it)

the page at https://documentation.onesignal.com/docs/links#handle-launch-url-on-mobile doens't provide an example for React-Native.
it says to see https://documentation.onesignal.com/docs/sdk-notification-event-handlers#, but that shows me this example for React-Native:
```
OneSignal.setNotificationOpenedHandler(openedEvent => {
  console.log("OneSignal: notification opened:", openedEvent);
  const { action, notification } = openedEvent;
});
```
which is what i'm doing and getting the above described result

**_edit:_**
this is without the addition to `AndroidManifest.xml`:

- when i perform a test notification without a `launchURL`, the app opens when the notification is clicked. 
- when i include a `launchURL`, the `setNotificationOpenedHandler` callback is called (the `openedEvent` gets printed to console), but the app is not opened when the notification is clicked.
- when the app is already open, it correctly sends me to the specified deeplink when the notification (which includes `launchURL`) is clicked

**_edit 2:_**
just tested on  RN@0.66.1 with RN-onesignal@4.3.1 on android 11 emulator and everything works as expected

**Comment by dkoeltringer** [comment]
With version 4.6.2 the problem was fixed for me - however, only for Google devices and not Huawei. Does somebody have the same situation?

**Comment by sclavijo93** [comment]
@jkasten2  I just updated to v4.3.3 and the first push is not opening the app yet :(

I've tested with react-native-onesignal 4.1.1 and 4.3.3 on the following phones:
- Xiaomi Redmi 8A (Android 10): when the user taps the push notification the app is not launching if is closed
- Xiaomi Redmi Note 10 Pro (Android 11): when the user taps the push notification the app is not launching if is closed
- Huawei P20 (Android 10): the app is launched when the first push is tapped
- Samsung Galaxy A01 Core (Android 10): the app is launched when the first push is tapped

<details><summary>Huawei P20</summary>


https://user-images.githubusercontent.com/19956031/147968269-90dd3337-9c16-4257-993e-27d300323e57.mp4
</details>


<details><summary>Xiaomi Redmi Note 10 Pro</summary>

https://user-images.githubusercontent.com/19956031/147968344-82816701-354d-4b70-8e4e-9d95c2d19343.mp4
</details>

Both examples are from the same apk

**Comment by AndrewShapovalov** [comment]
The same issue for Xiaomi Mi9T(Android 10):
`"react-native-onesignal": "^4.3.4"`

**Comment by sclavijo93** [comment]
@AndrewShapovalov I think my problem and yours are more related with [this issue](https://github.com/OneSignal/react-native-onesignal/issues/1309)

In my case it was because the new permission introduced in xiaomi :/

**Comment by rgomezp** [comment]
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1309
