### ISSUE TITLE
I updated onesignal app_id in my app but I still see users with new app in old app_id audience and not in a new one

### ISSUE THREAD

**Issue by beqramo** [OneSignal/react-native-onesignal#1296]
**Description:**

Hi, 
I changed my Onesignal app_id in my react native application, users updated the app but I can't see the users in the new app_id audience, I see them still in the old one, but I see that they updated the app and they are using up to date version. how can I get rid of this situation?

**Environment**

```json

"react-native-onesignal": "^4.3.0",
"react-native": "0.64.2",
```

**Steps to Reproduce Issue:**

1. create an app with one app_id and release it
2.  change app_id and release a new version.
3. you will see that users aren't moved to the new app_id audience, they are still in the old audience when I see that they updated the app.

**Comment by rgomezp** [comment]
Howdy,
Unfortunately, the push token registration won't change until one of the following occurs:
- The app is restored on a new device
- The user uninstalls/reinstall the app
- The user clears app data.

Can I ask why you chose to create a new OneSignal app? I would recommend to stick to the old one if possible so that you keep those subscribers.

Cheers

**Comment by beqramo** [comment]
we just had staging and prod app id, and in production, we run staging app id by mistake and after that, we changed it to the correct one. 

thank you for your answer.
