### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument

### ISSUE THREAD

**Issue by richardgirges** [OneSignal/react-native-onesignal#1361]
**Description:**
I am on a fresh install of React Native (0.67.1). I've configured and imported a fresh install of react-native-onesignal (4.3.6).

The moment I import the react-native-onesignal package, regardless of any method from the OneSignal package, I get the following error while running on iOS:

```
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
```

**Environment**
React Native 0.67.1
react-native-onesignal 4.3.6 (installed w/ yarn)
Running into error while running on iOS emulator (haven't tried Android yet)

**Steps to Reproduce Issue:**
* Setup a new react-native project
* Follow the steps outlined here: https://documentation.onesignal.com/docs/react-native-sdk-setup
* `yarn add react-native-onesignal`
* Import react-native-onesignal and execute any method (e.g., `OneSignal.setAppId`)

**Anything else:**

Call stack points to `react-native-onesignal/dist/index.js` L50:
```js
var eventManager = new EventManager_1.default(RNOneSignal);
```

**Comment by richardgirges** [comment]
Welp, I deleted `OneSignalNotificationServiceExtension` and re-added it and that resolved the issue. Not sure what I did wrong there. Closing this topic.

**Comment by oliviercperrier** [comment]
@richardgirges Im getting the same error with expo SDK 51 and react native 0.74.5 on a development build.. Not sure what to do to fix that

**Comment by delki8** [comment]
this is also happening to me, I still don't know the cause (removing and re-adding following onesignal's instructions did not help). I guess it's related to this line https://github.com/OneSignal/react-native-onesignal/blob/0fa9e05f7abe8e8249722a92151fa1b2112be352/src/events/EventManager.ts#L42, where the NativeEventEmitter is instantiated. The RNOneSignal variable might be null due to `NativeModules.OneSignal` also being null here: https://github.com/OneSignal/react-native-onesignal/blob/0fa9e05f7abe8e8249722a92151fa1b2112be352/src/index.ts#L42.

But I don't understand why would NativeModules, that come directly from 'react-native', would have a module called OneSignal. Maybe it should be added by some step that isn't running, but I can't figure out which one it is.

This is a small app that was recently migrated to RN 0.76.2, but I never really managed to put OneSignal to work on it.
