### ISSUE TITLE
Notification settings disappears when discarding the soft modal.

### ISSUE THREAD

**Issue by ignacio-sanhueza-ml** [OneSignal/react-native-onesignal#1371]
**Description:**

When asking for permissions, and using the soft prompt, if the "Maybe later" button is pressed to dismiss the soft prompt, the notifications setting disappears, so the user cannot change from their settings to allow/deny notifications.

**Environment**

react-native: 0.63.4
react-native-onesignal: 4.3.1

Installed through yarn.

**Steps to Reproduce Issue:**

1. Show the soft modal prompt through a trigger:
```
const { hasNotificationPermission, isSubscribed } =
      await OneSignal.getDeviceState();

    if (!hasNotificationPermission || !isSubscribed) {
      OneSignal.addTrigger('prompt_ios', 'true');
    }
```
2. When the soft prompt is shown, it has 2 buttons, one with the action Push Permission Prompt, and the other without a specific action, but the "Dismiss on click" option. Press the dismiss button or outside the soft prompt.
3. Check the app settings. The notification setting is gone.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/94488904/159286607-9bb7dec7-0138-47a4-902a-9ebaca9d7b7c.png">

In case you allow the notifications, the notifications options in the app settings appears.
The only way to make it appear again is to select allow notifications at the beginning.

**Comment by nan-li** [comment]
Hi @ignacio-sanhueza-ml,

For any iOS application, the notifications section won't appear in the app settings _until_ the native iOS push prompt dialog is shown (and will show up whether the user chooses Allow or Don't Allow). Try this out with any of your iPhone applications after first downloading them but before the push prompt is displayed. 

Since you can only show users the native push prompt one time, it's best not to show it if they are unsure about opting in yet and will choose "Don't Allow" (which is the reason for the "Maybe later" button). If the user chooses "Maybe later", the best practice is to not show the push prompt and try again later when you feel the user is more engaged, and use an in-app message pre-prompt again or programmatically show the native prompt with the method  `promptForPushNotificationsWithUserResponse`. 

Hope this helps!

**Comment by ignacio-sanhueza-ml** [comment]
Hello! thanks for the answer. So I will go for showing always the soft prompt, since you can only show once the native one.
Once again, thanks for your answer!
