### ISSUE TITLE
On removing the external user id when user logout from the app. The device status in OneSignal changes to never subscribed, which leads to sending notification fails.(Mobile Application - React Native)

### ISSUE THREAD

**Issue by Chandrakala0702** [OneSignal/react-native-onesignal#1384]
On user login, call the below method to set the external user-id under the particular device.

let externalUserId = '123456789'; // You will supply the external user id to the OneSignal SDK

```
// Setting External User Id with Callback Available in SDK Version 3.9.3+
OneSignal.setExternalUserId(externalUserId, (results) => {
  // The results will contain push and email success statuses
  console.log('Results of setting external user id');
  console.log(results);
  
  // Push can be expected in almost every situation with a success status, but
  // as a pre-caution its good to verify it exists
  if (results.push && results.push.success) {
    console.log('Results of setting external user id push status:');
    console.log(results.push.success);
  }
});
```
On user logout, call the below method to remove the external user-id under the particular device.

 ```
OneSignal.removeExternalUserId((results) => {
      // The results will contain push and email success statuses
      console.log('Results of removing external user id');
      console.log(results);
    });

```

**Comment by kesheshyan** [comment]
Thanks for reporting, we are looking into this.

**Comment by jennantilla** [comment]
@Chandrakala0702 apologies that this issue has gone stale. I'll be closing it out due to inactivity, but if you are still having issues please @ mention me and we can pick back up the conversation!

We have released a new User Model major release that offers many improvements and enhancements. I'd highly recommend upgrading to our [latest SDK version](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.1.2) and checking it out! Please see our [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/main/MIGRATION_GUIDE.md) for full details!
