### ISSUE TITLE
[ReactNative]: Disabled setWebContentsDebuggingEnabled

### ISSUE THREAD

**Issue by ocharlespereira** [OneSignal/react-native-onesignal#1409]
How can we help?
How disabled setWebContentsDebuggingEnabled debug mode in react-native-onesignal? I want to pass this parameter to false.

```
 // Allow Chrome Remote Debugging if OneSignal.LOG_LEVEL.DEBUG or higher
    private static void enableWebViewRemoteDebugging() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT &&
                OneSignal.atLogLevel(OneSignal.LOG_LEVEL.DEBUG)) {
            WebView.setWebContentsDebuggingEnabled(true);
        }
    }
```

**Comment by jkasten2** [comment]
@CharlesPereira1 This is due to the OneSignal log level setting as noted by the code comment. In the OneSignal example this is set high enough for this to be enabled. If you are running the example you can remove this line:
https://github.com/OneSignal/react-native-onesignal/blob/28e20c63f95256d423266a20021f6b579bfbb68e/examples/RNOneSignalTS/src/OSDemo.tsx#L39

**Comment by CharlesPereira1** [comment]
This command disabled setWebContentsDebuggingEnabled?

**Comment by ocharlespereira** [comment]
> @CharlesPereira1 This is due to the OneSignal log level setting as noted by the code comment. In the OneSignal example this is set high enough for this to be enabled. If you are running the example you can remove this line:
> 
> https://github.com/OneSignal/react-native-onesignal/blob/28e20c63f95256d423266a20021f6b579bfbb68e/examples/RNOneSignalTS/src/OSDemo.tsx#L39

This command disabled setWebContentsDebuggingEnabled?
