### ISSUE TITLE
[Bug]: VAPT issue found in react-native-onesignal for android.

### ISSUE THREAD

**Issue by somasekharkakarla** [OneSignal/react-native-onesignal#1465]
### What happened?

Our application recently went through VAPT. The team got back with a 2-low vulnerability 

1. The following activities are marked as exported in the manifest file, but those are not protected by any permissions. This can expose the mentioned activity to malicious apps running on the device. 
Activity (com.onesignal.NotificationOpenedActivityHMS)
Activity
(com.onesignal.NotificationOpenedReceiver) is not Protected. [android:exported=true]

2. The following receiver are exported, but not protected by any permissions. Failing to protect receiver could leave them vulnerable to attack by malicious apps. The receiver should be reviewed for vulnerabilities, such as injection and information leakage.
Broadcast Receiver (com.onesignal.UpgradeReceiver)
(com.onesignal.BootUp Receiver), (com.onesignal. NotificationDismissReceiver),
(com.onesignal. FCMBroadcastReceiver) is not Protected.
[android:exported=true]

<img width="591" alt="Screenshot 2022-12-08 at 5 59 12 PM" src="https://user-images.githubusercontent.com/65530762/206448546-b2301e03-2b87-4c43-a2d5-560050318f49.png">

@BritOneSignal @dean-onesignal @mtsay-onesignal Please hot-fix it and release it.

  

### Steps to reproduce?

```Markdown
VAPT process
```

### What did you expect to happen?

No VAPT Issues

### React Native OneSignal SDK version

4.3.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@somasekharkakarla apologies that this issue was missed. Since it's been quite some time since this was opened, I will be closing it due to inactivity. If you still have concerns surrounding penetration tests, please @ mention me and we can pick back up the conversation!

We have released a new User Model major release that offers many improvements and enhancements. I'd highly recommend upgrading to our [latest SDK version](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.1.2) and checking it out! Please see our [migration guide](https://github.com/OneSignal/react-native-onesignal/blob/main/MIGRATION_GUIDE.md) for full details!

Thanks!
