### ISSUE TITLE
[Bug]: Can't build android 31 with issue androidx.work:work-runtime

### ISSUE THREAD

**Issue by letruonglamit** [OneSignal/react-native-onesignal#1468]
### What happened?

Environment:
- React native: 0.61.5
- Platform: Android

I am trying to build the app but got the issue about androidx.work:work-runtime, In /android/app/build.gradle, I am using `androidx.work:work-runtime:2.7.1` for android 31 but got the issues `Could not resolve androidx.work:work-runtime:[2.1.0,2.6.99].` 

<img width="613" alt="Screen Shot 2022-12-23 at 12 49 56" src="https://user-images.githubusercontent.com/22797715/209279175-0fabd2ec-1b40-43d4-a1df-b70a97e72479.png">

### Steps to reproduce?

```Markdown
1. Install react-native-onesignal: "^4.5.0"
2. Run react-native run-android
```

### What did you expect to happen?

The app can run on Android

### React Native OneSignal SDK version

Release 4.5.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @letruonglamit apologies that this issue was missed.

I wanted to flag that our newest React Native release [5.0.5](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.0.5) has upgraded work-runtime dependencies [2.1.0, 2.8.99]. Please note that this includes breaking changes when upgrading from SDK 4.x.x. See our migration guide [here](https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md) for more details on upgrading.

Please let us know if you have any additional questions or concerns!
