### ISSUE TITLE
[question]: SDK methods never return a result, are there known causes?

### ISSUE THREAD

**Issue by liamjones** [OneSignal/react-native-onesignal#1477]
### How can we help?

We occasionally hit issues in dev where some SDK methods never seem to come back with a result - for example `OneSignal.removeExternalUserId()`. We don't seem to be able to find a consistent cause, it'll hang for a couple of people one day then work fine for them the next.

Are there known situations that can cause this? I haven't noticed API incidents via https://status.onesignal.com/ at the same time as we're getting the stalls.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @liamjones, the `OneSignal.removeExternalUserId()` method itself should return rather quickly, and does not have a return value.  I'm assuming you are referring to the callback provided as input to the method?

There is one case I know of where the callback provided may never get called.  If your app uses `OneSignal.setRequiresUserPrivacyConsent(true)` the `removeExternalUserId` callback will not get called back as the request was rejected due to privacy consent not being obtained.  There are other rare exceptional cases where your callback might not get called.  Both of these scenarios should be visible in the log however, and we could troubleshoot from there.

Other cases, your callback would get called once the operation has been completed with the backend API.  This may take some time depending on underlying conditions, but should get called.

Also are you seeing this on iOS, Android, or both platforms?
