### ISSUE TITLE
Unable to cancel notifications in android

### ISSUE THREAD

**Issue by pabloppp** [OneSignal/react-native-onesignal#149]
I try to clear a single notification by doing.
```
OneSignal.cancelNotification(notification.androidNotificationId);
```
But it doesn't seem to work
On the other hand 
```
OneSignal.clearOneSignalNotifications();
```
Works, but I am unable to decide what notifications to cancel...

**Comment by avishayil** [comment]
@pabloppp I'll take a look on this.
Thanks for reporting!

**Comment by Nightsd01** [comment]
@pabloppp apologies for the delay, I just tested this issue and it appears to be resolved in the SDK now, `OneSignal.cancelNotification(id)` appears to work without problems. Closing issue, please feel free to respond if you encounter further issues and I'll be happy to reopen.

**Comment by Gutyn** [comment]
Not sure if this is the right issue so let me know but in: 
`protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {..`
I'd like to cancel this particular notification for android (clear it from home screen) but I can't since `receivedResult` does not provide the int notificationId required to cancel a notification, please let me know what I'm missing.
