### ISSUE TITLE
How to show badge count on app's icon instead on red dot ?

### ISSUE THREAD

**Issue by janandaraj** [OneSignal/react-native-onesignal#1495]
### How can we help?

It says in **android** 

> The OneSignal SDK automatically sets the badge count on your app to the number of notifications that are currently in the notification shade

I can get red dot on app's icon when there is notification but i expect it to show as number instead of red dot ?

Observations:
Checked on app's settings i can see only two Options Badge --> dot or none (Number is not found), for other apps like instagram or whatsapp there is number icon and Number option available on notification settings.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @janandaraj!  The dot is supported by Android since v8.0, with the ability to "touch & hold" the app icon to see the number of outstanding notifications.

Only some devices support showing a number in the app badge itself.  Can you provide the device you are running on and we can take a look?

Thanks!

**Comment by janandaraj** [comment]
@brismithers Thanks for the response

I use **Realme 8** 4G variant running on **Android 12**
hope this helps

**Comment by jennantilla** [comment]
@janandaraj apologies that this issue has gone stale--I'm going to go ahead and close this out since it's been some time.

If this is still a concern for you please let us know.

You could check your device and see if a badge count is configurable. You can try:

Notification and status bar > Manage Notification > Badge > Number or Dot

From what I've read, it may not be an option on some Realme devices. Are any other apps on your device showing badge counts? 

Thanks!
