### ISSUE TITLE
Build Error Without Using CocoaPods

### ISSUE THREAD

**Issue by kelvinaliyanto** [OneSignal/react-native-onesignal#152]
When we opt to not use CocoaPods, does the current react-native-onesignal 3.0.0 working with react-native 0.40? I keep getting OneSignal/OneSignal.h file not found. The last time I use react-native-onesignal 1.2.3 with react-native 0.34, it is still working without using CocoaPods. Do we have to use CocoaPods when dealing with react-native-onesignal 3.0.0 and react-native 0.40?

**Comment by avishayil** [comment]
@kelvinaliyanto to be honest, I haven't tried not to use CocoaPods on the new version, but @eriksape have some experience with it and his PR #151 contains some examples i'm about to test and see if it has any problems.
Generally, you don't have to use CocoaPods, you can use Carthage or link the framework yourself, but I suspect that the library is built to be supported with CocoaPods, because of the <OneSignal/OneSignal.h> include.

**Comment by kelvinaliyanto** [comment]
@avishayil if we opt to not use either CocoaPods or Carthage, and we choose to link the framework ourself, can you tell me what is your OneSignal Framework version is? I downloaded the latest one at https://github.com/OneSignal/OneSignal-iOS-SDK (v2.3.5). But the framework actually includes OneSignal.h inside the Header folder.

**Comment by avishayil** [comment]
I'll try to set up a project without CocoaPods and let you know.

**Comment by Lepozepo** [comment]
I am getting the same issue :/

**Comment by avishayil** [comment]
I got it to work, going to upload more detailed instructions about this.
@kelvinaliyanto @Lepozepo

**Comment by Lepozepo** [comment]
Thanks @avishayil :D

**Comment by avishayil** [comment]
@kelvinaliyanto @Lepozepo 

Ok, so the only way I figured so far:
1. Download the most recent `OneSignal.framework` from their website.
2. Drag it to the `Frameworks` folder on your project and mark the `Copy if needed` thing.
3. Drag it from the newly created `Frameworks` folder to `RCTOneSignal.xcodeproj` on your `Libraries` section, mark the `Copy if needed` thing again.
4. Clean and rebuild.

I have no idea why it works like that, and why do we need the `OneSignal.framework` twice, but the issue is:

1. If you don't add the framework file to the `RCTOneSignal.xcodeproj` project, it would complain about `<OneSignal/OneSignal.h>` being not found.
2. If you don't add the framework file to the main project target, it would complain about `ld: framework not found OneSignal`.

So as a workaround for now, just add it to both locations, and it would work.
I tried to find a alternative solution but came out with nothing. Maybe @jkasten2 will pour some light here about why it happens and how can you solve it.

**Comment by avishayil** [comment]
Please take a look on this example:
https://github.com/geektimecoil/react-native-onesignal/tree/master/examples/ios/OneSignalWithoutCocoa

**Comment by TheIrvingBarajas** [comment]
Hey @avishayil , 

I followed your suggestion and it got rid of my 'OneSignal/OneSignal.h file not found'  error (^.^).
 But I am now getting 'RCTBridgeModule.h file not found' inside RCTOneSignal.h file. Any insight would be greatly appreciated

**Comment by avishayil** [comment]
Can you provide access to a repo with the issue?

**Comment by TheIrvingBarajas** [comment]
Unfortunately, I am unable to at this time.

**Comment by avishayil** [comment]
What version of RN are you using, and what version of `react-native-onesignal`?

**Comment by nonameolsson** [comment]
I'm getting a similar error message #243 
Could it have something to do with this?
