### ISSUE TITLE
[Bug]: promptForPushNotificationsWithUserResponse alert messages language

### ISSUE THREAD

**Issue by whyamsx** [OneSignal/react-native-onesignal#1563]
### What happened?

[This](https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/src/main/res/values/strings.xml) messages require translation capability in **promptForPushNotificationsWithUserResponse** method with **true** first param
I want set another language to this messages, but not have possibility

### Steps to reproduce?

```Markdown
1. Use OneSignal.promptForPushNotificationsWithUserResponse(true) method with the first parameter true.
2. Look at the Alert by switching different languages on the device or through OneSignal.setLanguage(...), the language will be the same
```

### What did you expect to happen?

Some additional parameter for options, with the ability to set translation for these messages,
or so that **setLanguage** method already provides me with translation into the available languages

### React Native OneSignal SDK version

4.8.5

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @whyamsx apologies that this issue was missed.

You can configure an in-app message permission prompt in custom languages. 

More information here: https://documentation.onesignal.com/docs/how-to-prompt-for-push-permissions-with-an-in-app-message

Please let us know if you have any additional questions or concerns!
