### ISSUE TITLE
[question]: OneSignal.sendTag gives undefined is not a function in react native on android device

### ISSUE THREAD

**Issue by Vinita-16** [OneSignal/react-native-onesignal#1652]
### How can we help?

I am having issues in integrating OneSignal into my react native app. This is the code I have used for initialization.

// OneSignal Setup
  useEffect(() => {
    OneSignal.Debug.setLogLevel(LogLevel.Verbose);

    // OneSignal Initialization
    OneSignal.initialize('OneSignal_App_Id');

    // requestPermission will show the native iOS or Android notification permission prompt.
    // We recommend removing the following code and instead using an In-App Message to prompt for notification permission
    OneSignal.Notifications.requestPermission(true);
    // Method for listening for notification clicks
    OneSignal.Notifications.addEventListener('click', event => {
      console.log('OneSignal: notification clicked:', event);
    });
  },[]);

And Now I am trying to send tag using OneSignal, it is giving an error undefined is not a function for sendTag function.

      OneSignal.sendTag("Event tag", currentDateUnixTimestamp, tagsSent => {
        console.log('EVENT TAG SENT', tagsSent);
     })

It would be helpful if anyone can list out the steps to integrate this library into react native.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dervstudio** [comment]
Try to use `OneSignal.User.addTag(key, value);`

**Comment by Vinita-16** [comment]
> Try to use `OneSignal.User.addTag(key, value);`

@dervstudio, I have added that in the code. Actually sendTag function is not available in OneSignal package.

**Comment by jennantilla** [comment]
@Vinita-16 apologies that this issue was missed. As discussed, `sendTag` is not a method on the most current major release (`addTag` is the method to use). 

I'm going to close this issue due to inactivity. If you are you still having issues with this new method? If so can you please share the [debug log](https://documentation.onesignal.com/docs/capturing-a-debug-log#get-the-logs) reproducing the behavior we'll be happy to take a look!

Thanks!
