### ISSUE TITLE
[question]: Best way to integrate OneSignal to subscribe VoIP push in another native module 

### ISSUE THREAD

**Issue by tair-rhyme** [OneSignal/react-native-onesignal#1732]
### How can we help?

Hi, We are working on a project where we need to integrate the react-native-onesignal module with another native React Native module to receive VoIP push notifications and pass the information to a dialer. Could you please guide me on how to achieve this integration?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @tair-rhyme thanks for reaching out! The OneSignal SDK does not currently register VOIP push tokens. However, you can setup your app to collect them and send it to OneSignal in order to use our service for VOIP messages.

Please see our [VoIP Notifications guide](https://documentation.onesignal.com/docs/voip-notifications) for more details and setup steps. Let us know if you have any additional questions or concerns!
