### ISSUE TITLE
Onesignal.h file not found

### ISSUE THREAD

**Issue by radiegtya** [OneSignal/react-native-onesignal#19]
in my xcode proj, I can't build my project.

<img width="762" alt="onesignalerr" src="https://cloud.githubusercontent.com/assets/2161622/14587677/fc35c7a2-04e0-11e6-8258-93d8c6259e85.png">

**Comment by algosubi** [comment]
i have same problem

**Comment by francocorreasosa** [comment]
You can fix it by adding the OneSignal library though CocoaPods.

**Comment by radiegtya** [comment]
Never use cocoapods before, but I'll try

**Comment by avishayil** [comment]
Please add the necessary Pod, since it's part of the setup process.

**Comment by lucasyalap** [comment]
If you don't want to use CocoaPods and correct follow this 2 steps 
1. Add OneSignal.framework that is in ../node_modules/react-native-onesignal/ios/Frameworks/OneSignal.framework in YourProject > Build Phases > Link Binary With Libraries
2. Add "$(SRCROOT)/../node_modules/react-native-onesignal/ios/Frameworks" in YourProject > Build Settings > Framework Search Paths

**Comment by radiegtya** [comment]
Aleready did this, but still error.

**Comment by lucasyalap** [comment]
Please can you show us : 
- Screenshot of code error (again)
- YourProject > Build Phases >  Link Binary With Libraries
- YourProject > Build Settings > Framework Search Paths

Because normally if did what i said it works.

**Comment by radiegtya** [comment]
Here is my screenshot, sorry for very late response, please help @lucasyalap:

<img width="1280" alt="onesignal_1" src="https://cloud.githubusercontent.com/assets/2161622/18300549/a75c15f6-74fc-11e6-8110-1a44fd22634a.png">
<img width="1280" alt="onesignal_2" src="https://cloud.githubusercontent.com/assets/2161622/18300551/a7bda5aa-74fc-11e6-9e95-8165bfd3faf2.png">
<img width="1279" alt="onesignal_3" src="https://cloud.githubusercontent.com/assets/2161622/18300552/ab3c157c-74fc-11e6-91db-0336fda0888b.png">

**Comment by radiegtya** [comment]
RCTOnesignal.h already found. Now I have new problem, when using xcode:

<img width="1280" alt="onesignal_4" src="https://cloud.githubusercontent.com/assets/2161622/18300801/1a798d78-74ff-11e6-8804-f7891fa43b81.png">

While using cocoapod, I had different error message:

<img width="1280" alt="onesignal_5" src="https://cloud.githubusercontent.com/assets/2161622/18300819/4424b602-74ff-11e6-9374-6de356e551c0.png">

Please help

**Comment by lucasyalap** [comment]
If you realy don't want to use pods, you have to remove all about pods
1.  In left panel remove pods project
2. In Left panel remove pods directory
3. in "YourProject > Build Phases > Link Binary With Libraries" remove libPods-OneSignal.a
4. "YourProject > Build Settings > Framework Search Paths" remove "$(PODS_ROOT)/OneSignal/IOS_SDK/Frameworks"

If you have any other errors please send screenshot

**Comment by radiegtya** [comment]
THanks a lot @lucasyalap, now all the error had gone.
And the user already registered on onesignal users list.
But ios simulator can't receive the push notif, I'll test tomorrow on real device and share with you if fail or success. Btw why don't author of this package suggest those simple step by step like yours rather than using pods? Regards

**Comment by jakeatwork** [comment]
i'm on react-native 0.37 and here's how i was able to get this to work (i think the readmes/documentation are slightly behind react native).

1. on a clean branch with none of the onesignal work...
2. run `npm install react-native-onesignal --save`
3. run `react-native link`
4. for iOS follow the podfile instructions (be sure to follow the react native version note carefully)
5. for iOS follow the code additions in the instructions
6. for android follow the android instructions (most of the code should be there from the link command, but double check everything)
7. for android be sure to use `import com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage;` and NOT `import com.geektime.rnonesignal.ReactNativeOneSignalPackage;` (some old documentation had the rnonesignal and that's since been updated)
8. then complete config and setup and all files 
9. hopefully that does the trick for you...please reply if you have any issues as i spent some time on both android and iOS over a few branches to get this to work.

YMMV if you are using something lower than v0.37 of RN. good luck.
