### ISSUE TITLE
RNOneSignal example doesn't work

### ISSUE THREAD

**Issue by bitsal** [OneSignal/react-native-onesignal#198]
I don't know how you test your commits and examples but I couldn't run your example in general.
I've been following your README steps
```
git clone https://github.com/geektimecoil/react-native-onesignal
cd react-native-onesignal && cd examples && cd RNOneSignal
yarn && cd ios && pod update && cd ..
```
And I've got `[!] No 'Podfile' found in the project directory.` because there is no such file.

**Comment by dwilt** [comment]
@bitsal you need to create a Podfile first in your iOS directory. This is like npm, but manages iOS specific plugins that a lot of react native projects rely on. The current README steps don't very well explain this. Go create a Podfile, add `OneSignal` to it, which will look something like this:

```
workspace 'YourProjectName.xcworkspace'
project 'YourProjectName.xcodeproj'

target 'YourProjectName' do
    pod 'OneSignal'
end
```

Then try `pod install` instead of `pod update`.

**Comment by bitsal** [comment]
@dwilt Thank you! I know how to make it workable. I'm talking about the example that doesn't work out-of-the-box. I don't think it's a big deal to add this Podfile under Git. Or README should be updated with code block like above one.

**Comment by bitsal** [comment]
Good!
