### ISSUE TITLE
Notification has "bell" icon for some reason

### ISSUE THREAD

**Issue by GeoffreyPlitt** [OneSignal/react-native-onesignal#223]
We recently updated our version of this lib and now the icon on any PN is just a generic "Bell". It used to be our app's icon, but no longer.

Anyone know how to fix it, or where we control this?

**Comment by jkasten2** [comment]
@GeoffreyPlitt In the Android Native 3.0.0 version the bell was added as default instead of using the app icon. This is because as of Android 5 the small notification icon is forced to be all white which for most app icons will just looks like a white square.

See the follow documentation to customize the Android Notification icon.
https://documentation.onesignal.com/docs/customize-notification-icons

**Comment by ShridharCodewave** [comment]
I have the same issue and I followed the instructions provided at
https://documentation.onesignal.com/docs/customize-notification-icons but it didn't work.
Is there anyway we can set the small_icon in rest API?

**Comment by mounikakella** [comment]
I am also facing the issue, how to change default bell icon in android to custom icon in react native? I have added drawable-* in android/app/src/main/res with white icons.

**Comment by anastely** [comment]
are you found any solution, I'm still facing this issue this time :)?

**Comment by anastely** [comment]
@mounikakella are you found any solution, I'm still facing this issue this time :)?
