### ISSUE TITLE
What does .configure do?

### ISSUE THREAD

**Issue by nickpedersen** [OneSignal/react-native-onesignal#337]
We've been running OneSignal in production for a few months now and we're seeing crashes on Android as described here: https://github.com/OneSignal/OneSignal-Android-SDK/issues/277

I've noticed that the stack trace shows that this error is coming from `OneSignal.configure()`, which we're calling when our component mounts, but on investigation there's no documentation about the purpose of calling this method.

In testing my app still seems to function and receive push notifications correctly without running the `configure` function. I've been having a hard time reproducing the error above, we've only seen it in user crash logs, so I can't yet say whether this does in fact fix the problem, but I'm hopeful.

I'm wondering whether I can safely remove the `configure` call? It seems to be a throwback to an old API but there are a few issues, such as #200, which make me hesitant to remove the call.

What is the purpose of `configure` since v3.0.2? Is the code that's associated with the method left over and on the roadmap to be migrated later?

**Comment by Nightsd01** [comment]
Hi @nickpedersen , sorry for the long delay, I've recently started working on OneSignal and I'd like to help you if you're still seeing these crashes.

The `configure()` function calls the `idsAvailable:` method in the iOS SDK, which eventually causes the `ids` event to be called in React providing the userId and push token. If you are still seeing crashes could you send me a stack trace?

Due to inactivity I'll close this issue but if you're still seeing it feel free to reply and I will reopen.
