### ISSUE TITLE
It would be great if we could set callback for sendTags onSuccess and onFailure

### ISSUE THREAD

**Issue by 7kfpun** [OneSignal/react-native-onesignal#360]
https://github.com/geektimecoil/react-native-onesignal/blob/88f00a6f30bbf2986a570f908cff877b8ef71883/ios/RCTOneSignal/RCTOneSignal.m#L237-L242

**Comment by Nightsd01** [comment]
The iOS SDK has this functionality, however the Android SDK is a little bit more complex since calling the sendTags function doesn't directly trigger an HTTP request and instead it just updates a property that gets synchronized at a later time with OneSignal

This is definitely a good idea though and we will make a note of it, thank you

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
