### ISSUE TITLE
 onRegistered method not working 

### ISSUE THREAD

**Issue by joyo43** [OneSignal/react-native-onesignal#390]
`  onRegistered(notifData) {
    console.log("Device had been registered for push notifications!", notifData);
  }`
i want to store player id into my database  when user registers for the push notification .

**Comment by sunweiyang** [comment]
The `onRegistered` event has been removed, as of 8acf1b89ed4cb0456c62254fa0728f4abf4c4c5f by @Nightsd01. It looks like if we want to use `onRegistered`, we'll have to roll back to `react-native-onesignal@3.0.9` or earlier.

@Nightsd01: @joyo43 and I (and probably others) need `onRegistered` for our apps -- if we can't use `onRegistered` anymore, what is now your recommended way to get OneSignal user registration the moment it happens?

**Comment by Nightsd01** [comment]
@joyo43 @sunweiyang 

The reason it was removed was because, as far as I could tell, it was never called under any circumstances. In fact, if I looked back through the history of the SDK, I could _never_ see any code that triggered this event.

Currently, whenever the user's subscription status changes, the `onIds()` event gets called. I would suggest using this event instead,
