### ISSUE TITLE
Problem send notification

### ISSUE THREAD

**Issue by DarkXelus** [OneSignal/react-native-onesignal#406]
Hello,
I can not send a notification from a button in my application.
i try with the code next for send a notification: 

`   let contents = {
     'en': 'You got notification from user'
   }
   OneSignal.postNotification(contents, token);`

This returns me the following error : JSON value ' ' of type NSString cannot be converted to 
NSDictionary 

Someone can help me?
Thank

**Comment by Nightsd01** [comment]
@DarkXelus this isn't a bug with the SDK, you should have more than two arguments when calling `postNotification`. 

For example:

```javascript
OneSignal.postNotification(contents, additionalData, userId, otherParameters);
```

The user ID is required (so OneSignal knows who it needs to send this push notification to). 

However, the `additionalData` and `otherParameters` fields are optional, so you can just write this instead of you want:

```javascript
OneSignal.postNotification(contents, {}, playerId, {});
```
