### ISSUE TITLE
problem in huawei notification

### ISSUE THREAD

**Issue by KianooshSoleimani** [OneSignal/react-native-onesignal#415]
i use this version of react-native
"react": "16.0.0-beta.5",
		"react-native": "0.49.0",
		"react-native-onesignal": "^3.1.1",

but notification not working for me in hawei android 7

**Comment by Nightsd01** [comment]
I am closing this issue due to a total lack of detail....

Please add some more information and I'll be happy to reopen your issue.

Here are some examples of information you will want to add...

0. Do you mean it works on other android devices, just not Huawei devices?
1. Does it work in iOS?
2. Did it suddenly stop working or did it never work?
3. Have you carefully followed the readme instructions to set up the onesignal SDK in your project?
4. Do you see any errors printed to logcat?
5. Do you see any errors in the OneSignal dashboard?

**Comment by mstf0ta-app** [comment]
i have same problem
in emulator and galaxy everything is good
but when i use huawei the app not received notifications when app in background or killed
but it received when the app is in foreground
