### ISSUE TITLE
Support run onReceived event in JS, even when the app isn't running at all

### ISSUE THREAD

**Issue by gaboelnuevo** [OneSignal/react-native-onesignal#423]
See: https://github.com/zo0r/react-native-push-notification/pull/220/

**Comment by Nightsd01** [comment]
We currently have no plans to add JS background events. 

You _can_ use the `content-available` flag, if the app is still running (but in the background) it will correctly call the `onReceived` JS event.

However if the app is completely terminated (either intentionally or due to being closed by iOS), the only way to do background processing is by using a Notification Service Extension (we have instructions for this on the readme).

The Notification Service Extension is essentially like a very tiny process/executable that is separate (but tied to) your main application. It is very limited in terms of memory/resources/time. Loading the React runtime would be implausible and wasteful and could negatively impact the delivery of notifications. 

We are considering, however, doing something a bit more minimal (perhaps loading a single .js file and calling a function). That might work. Thank you for your suggestion

**Comment by gaboelnuevo** [comment]
I think that load a headless task will be nice. Thanks you.
