### ISSUE TITLE
One Signal can't register my device

### ISSUE THREAD

**Issue by duytq94** [OneSignal/react-native-onesignal#432]
Hi all, I have a issue but don't know how to fix it.
Most device (even emulator) can be register with one signal and receive notification but my device (Asus Z00AD Zenfone 2 ZE551ML) does not receive notification at all. Then I check the value of param "device" on function onIds() and know that pushToken has null value. And list users in onesignal website don't have my device too.
I don't know why this happen only on my device.
Wish you can help, thanks alot.

**Comment by Nightsd01** [comment]
@duytq94 This is a very vague issue. Are you seeing any errors printed to logcat? Can you set OneSignal log level = verbose?

**Comment by duytq94** [comment]
@Nightsd01 
![image](https://user-images.githubusercontent.com/24253421/37838599-eb8a0194-2eea-11e8-9b49-655189e5d1f5.png)
This is the info when I log in verbose.
I don't get anything more info than that in log.

**Comment by Nightsd01** [comment]
@duytq94 If the SDK works fine on all devices except for one particular device, it could be multiple issues. Does the device use Google Play services, or does it get push notifications through some other provider?

In any case, since it's only happening with one particular device, it wouldn't be an issue with the react-native-onesignal SDK, I would recommend that you contact OneSignal support at https://www.onesignal.com
