### ISSUE TITLE
Invalid bitcode version Xcode 

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [OneSignal/react-native-onesignal#439]
I got this err while generating build

```
error: Invalid bitcode version (Producer: '802.0.42.0_0' Reader: '800.0.42.1_0')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Nightsd01** [comment]
I am closing this issue due to a lack of details.....

If you can provide some more information I would be happy to reopen and investigate the issue.

Can you tell me:

1. Why do you think this issue is related to the OneSignal react native SDK?
2. What version of the SDK are you using?
3. Did you make a change that caused this issue to occur?

**Comment by alikh31** [comment]
I came around the same issue after adding OneSignal SDK to my app, the issue will get solved it you disable bitcode for both main project and service extension project (Project Settings > Build settings > Enable Bitcode > NO)

My guess is the OneSignal project itself has the bitcode disabled and to have the bitcode enable for your main project all subproject have to have it enabled.
