### ISSUE TITLE
RN crashes 

### ISSUE THREAD

**Issue by olup** [OneSignal/react-native-onesignal#44]
App crashes regularly when developing, here with RN 0.2 and android 6. This happens only after integrating OneSignal RN component. This is pretty vague, any leads to track down this bug ?

**Comment by avishayil** [comment]
Any stacktrace?

**Comment by avishayil** [comment]
@olup Please post the error message & stack trace so we'll be able to track down this issue.

**Comment by olup** [comment]
Sometime there is no error message, sometime it says just " xxx has ended ". Can you give directions to recover stack trace after crash ?

**Comment by avishayil** [comment]
Go to Android Studio and copy the latest log lines before the crash.
Or simple open a terminal and type “adb logcat” when the device is
connected via USB.
Find the appropriate lines and paste them here.

On June 20, 2016 at 12:33:04 PM, olup (notifications@github.com) wrote:

Sometime there is no error message, sometime it says just " xxx has ended
". Can you give directions to recover stack trace after crash ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/geektimecoil/react-native-onesignal/issues/44#issuecomment-227094257,
or mute the thread
https://github.com/notifications/unsubscribe/AAyekFM0qtB4Ird-AoKxTqHG0JZasjhFks5qNl5QgaJpZM4I4JYp
.

**Comment by avishayil** [comment]
I'm closing this issue for now. If you have any more information, I'll be glad to try help.

**Comment by olup** [comment]
Yes ok, i'll be back with data as soon as i get time. The problem doesn't
happen after release tho, so no hurry.

2016-06-22 16:52 GMT+02:00 Avishay Bassa notifications@github.com:
