### ISSUE TITLE
E/OneSignal: Error Getting Google Registration ID (android)

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#467]
Getting error on android and it return pushToken: null

```
E/OneSignal: Error Getting Google Registration ID
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzs;
        at com.google.android.gms.iid.zzaa.zzdr(Unknown Source:17)
        at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source:3)
        at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:7)
        at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:167)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzs" on path: DexPathList[[zip file "/data/app/com.test.app-PN2Q7FjFYm1evcEmKKNElg==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.app-PN2Q7FjFYm1evcEmKKNElg==/lib/arm, /system/fake-libs, /data/app/com.test.app-PN2Q7FjFYm1evcEmKKNElg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.iid.zzaa.zzdr(Unknown Source:17) 
        at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source:3) 
        at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:7) 
        at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:167) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by ntnamag** [comment]
Same problem with you

**Comment by zoi-aoba** [comment]
with you

**Comment by Nightsd01** [comment]
Can you add some more information? 

- Does this issue occur only on one device or multiple devices?
- Simulator or real devices?
- How did you install react native onesignal into your project?
- Are you using the latest version of the SDK?

**Comment by Nightsd01** [comment]
In the latest SDK updates (3.2.1) we made some large changes to GCM/FCM and fixed some thread synchronization issues that likely resolve this problem. 

I am assuming due to a lack of response that this issue has been resolved. Please feel free to reply if anyone encounters this issue and I'll be happy to reopen & investigate

**Comment by EJohnF** [comment]
@Nightsd01 actually it keeps failing for me even on 3.2.2

`
FATAL EXCEPTION: main
Process: com.getcodified.scooch, PID: 10859
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6460)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6052)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5991)
	at android.app.ActivityThread.-wrap3(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1727)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/com.getcodified.scooch-2/base.apk"],nativeLibraryDirectories=[/data/app/com.getcodified.scooch-2/lib/arm, /data/app/com.getcodified.scooch-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 12 more`

I can add that before I've used a fork from this commit:
https://github.com/geektimecoil/react-native-onesignal/commit/b291efff8ab3cf7c80ca797cb8bafd5712081d02

But then I was need new features, add 3.2.1 SDK, and it crash android on start. Also checked that 3.2.0 - also faild.

- checked on simulator and real device
- install using react-native link, and fixes in manifest
- check different

**Comment by ntnamag** [comment]
I fixed with `compile "com.google.android.gms:play-services-base:+"`

**Comment by EJohnF** [comment]
nope, it didn't help for us. 

btw, our original dependencies list: 

```
dependencies {
    compile project(':react-native-onesignal')
    compile project(':react-native-branch')
    compile project(':react-native-background-timer')
    compile project(':react-native-google-fit')
    compile project(':react-native-fbsdk')
    compile project(':react-native-keychain')
    compile project(':react-native-background-upload')
    compile project(':react-native-i18n')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-wheel-picker')
    compile project(':react-native-blur')
    compile project(':react-native-vector-icons')
    compile(project(':react-native-svg')) {
        exclude group: "com.android.support", module: "appcompat-v7"
    }
    compile project(':lottie-react-native')
    compile project(':instabug-reactnative')
    compile project(':bugsnag-react-native')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.airbnb.android:lottie:1.5.3'
}
```

**Comment by sinapcs** [comment]
I have this problem too. this is my log:

`
05-16 21:14:00.334  1535  1535 E AndroidRuntime: FATAL EXCEPTION: main
05-16 21:14:00.334  1535  1535 E AndroidRuntime: Process: com.appechteachers, PID: 1535
05-16 21:14:00.334  1535  1535 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(ActivityThread.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.os.Looper.loop(Looper.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
05-16 21:14:00.334  1535  1535 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/com.appechteachers-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appechteachers-1/lib/arm, /data/app/com.appechteachers-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        ... 12 more
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.zzbq
05-16 21:14:00.334  1535  1535 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 21:14:00.334  1535  1535 E AndroidRuntime:                ... 13 more
05-16 21:14:00.334  1535  1535 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
`

**Comment by ntnamag** [comment]
```
defaultConfig {
        applicationId "info.khoahocdoisong.app"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 30
        versionName "3.0.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [onesignal_app_id: "", onesignal_google_project_number: "REMOTE"]
    }
    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
    }
    packagingOptions {
        pickFirst 'META-INF/*'
    }
```
`compile 'com.android.support:multidex:1.0.1'`
In MainApplication.java
```
import android.content.Context;
import android.support.multidex.MultiDex;
...
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
```

**Comment by adamivancza** [comment]
@ntnamag that doesn't work either :/

**Comment by ntnamag** [comment]
@adamivancza You should disable Proguard in app/build.gradle
`def enableProguardInReleaseBuilds = false`
I don't known about this error, but i disable it and rebuild work fine

**Comment by adamivancza** [comment]
@ntnamag yeah that's already set - here is our complete build.gradle file: https://gist.github.com/adamivancza/2cf3dc2d8dc3ec995e79d8cf1419bcef

**Comment by ntnamag** [comment]
@adamivancza Are you fix it?

**Comment by adamivancza** [comment]
Sadly not - still crashes on launch

**Comment by ntnamag** [comment]
Are you crash app on Android version?

**Comment by adamivancza** [comment]
Yes - https://github.com/geektimecoil/react-native-onesignal/issues/467#issuecomment-389300697

**Comment by ntnamag** [comment]
My build.gradle

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.9.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}


apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "info.khoahocdoisong.app"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 30
        versionName "3.0.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [onesignal_app_id: "", onesignal_google_project_number: "REMOTE"]
    }
    dexOptions {
        jumboMode true
        javaMaxHeapSize "4g"
    }
    packagingOptions {
        pickFirst 'META-INF/*'
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-appstore-version-checker')
    compile project(':react-native-version-number')
    compile project(':react-native-fbsdk')
    compile project(':react-native-fbads')
    compile project(':react-native-android-wv-video')
    compile project(':react-native-video')
    compile project(':react-native-vector-icons')
    compile project(':react-native-splash-screen')
    compile project(':react-native-share')
    compile project(':react-native-orientation')
    compile project(':react-native-onesignal')
    compile project(':react-native-keep-awake')
    compile project(':react-native-immersive')
    compile project(':react-native-fast-image')
    compile project(':react-native-code-push')
    compile project(':react-native-admob')
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:27.1.1'
    compile 'com.android.support:cardview-v7:27.1.1'
    compile 'com.android.support:animated-vector-drawable:27.1.1'
    compile 'com.android.support:customtabs:27.1.1'
    compile 'com.android.support:recyclerview-v7:27.1.1'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.facebook.react:react-native:+'
    compile "com.google.android.gms:play-services-base:+"
    compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-common:+"
    compile "com.google.firebase:firebase-iid:+"
    compile "com.google.android.gms:play-services-gcm:+"
    compile "com.google.android.gms:play-services-location:+"
    compile "com.google.android.gms:play-services-ads:+"
    // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```

My Application.java

```
package info.khoahocdoisong.app;

import android.app.Application;
import android.content.Context;
import android.support.multidex.MultiDex;

import com.akulyk.react.androidwebview.AndroidWebViewPackage;
import com.brentvatne.react.ReactVideoPackage;
import com.corbt.keepawake.KCKeepAwakePackage;
import com.dylanvann.fastimage.FastImageViewPackage;
import com.facebook.CallbackManager;
import com.facebook.appevents.AppEventsLogger;
import com.facebook.react.ReactApplication;
import com.masteratul.RNAppstoreVersionCheckerPackage;
import com.apsl.versionnumber.RNVersionNumberPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.soloader.SoLoader;
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
import com.github.yamill.orientation.OrientationPackage;
import com.microsoft.codepush.react.CodePush;
import com.oblador.vectoricons.VectorIconsPackage;
import com.rnimmersive.RNImmersivePackage;
import com.sbugert.rnadmob.RNAdMobPackage;

import org.devio.rn.splashscreen.SplashScreenReactPackage;

import java.util.Arrays;
import java.util.List;

import cl.json.RNSharePackage;
import io.callstack.react.fbads.FBAdsPackage;

public class MainApplication extends Application implements ReactApplication {
    private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

    protected static CallbackManager getCallbackManager() {
        return mCallbackManager;
    }

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }

        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
            new RNAppstoreVersionCheckerPackage(),
            new RNVersionNumberPackage(),
                    new FBSDKPackage(mCallbackManager),
                    new FBAdsPackage(),
                    new AndroidWebViewPackage(),
                    new ReactVideoPackage(),
                    new VectorIconsPackage(),
                    new SplashScreenReactPackage(),
                    new RNSharePackage(),
                    new OrientationPackage(),
                    new ReactNativeOneSignalPackage(),
                    new KCKeepAwakePackage(),
                    new RNImmersivePackage(),
                    new FastImageViewPackage(),
                    new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG),
                    new RNAdMobPackage()
            );
        }

        @Override
        protected String getJSMainModuleName() {
            return "index";
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    @Override
    public void onCreate() {
        super.onCreate();
        AppEventsLogger.activateApp(this);
        SoLoader.init(this, /* native exopackage */ false);
    }
}

```

**Comment by adamivancza** [comment]
Oh damn I completely missed these hidden notes here: https://github.com/geektimecoil/react-native-onesignal/blob/master/android/build.gradle#L74

that seems to solve our problem... @Nightsd01 could you update docs to highlight this? maybe someone also faces this issue.

**Comment by jamesone** [comment]
Any update? I'm having the same issue

**Comment by rcidt** [comment]
I want to echo what @adamivancza said. It fixed my issue.

You guys should definitely add that note to the readme.

**Comment by jkasten2** [comment]
@rcidt This is part of the main setup guide OneSignal's documentation site.
https://documentation.onesignal.com/docs/react-native-sdk-setup#section-adding-the-gradle-plugin

**Comment by hugoh59** [comment]
I have that and still getting this issue.
