### ISSUE TITLE
why i don't see the react-native-onesignal.podspec in the node_modules/react-native-onesignal folder ??? 

### ISSUE THREAD

**Issue by drtapha** [OneSignal/react-native-onesignal#479]
i install react-native-onesignal using yarn. 
After installation , i want use the react-native-onesignal with cocoapods  but i don't see the podspec in the node_modules/react-native-onesignal folder

**Comment by lucarge** [comment]
Because it hasn't been released yet. The [commit](https://github.com/geektimecoil/react-native-onesignal/commit/620717a0027538999cd98e1f225d0e4d9a804445) is already merged in `master`, so you only need to wait until version `3.1.5` will be released.
You can point your dependency to the commit above in the meantime if you can't wait for the next release 😉
