### ISSUE TITLE
expo detached app ios build failed after setup this sdk

### ISSUE THREAD

**Issue by proguru58** [OneSignal/react-native-onesignal#483]
I have followed the instructions for React Naive SDK setup and got the following error message in compiling ios building in my expo detached xcode project.

/React/Core/Base/RCTConvert.h:13:9: 'React/RCTAnimationType.h' file not found

**Comment by Nightsd01** [comment]
Hi @proguru58 , this indicates a linking error with React Native. Can you describe what steps you used after detaching?

PS: we’re about to come out with an update that will make it much easier to use OneSignal in Expo projects. You still won’t be able to receive push notifications before you detach using OS, but you will at least be able to run your app in Expo. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nightsd01** [comment]
Your particular issue is not an issue with the OneSignal SDK, it's a linking issue with react native in general.

However, we've changed the SDK (#485) so that it will no longer crash Expo projects before being detached. This means you can develop with Expo without having to do any fancy conditional imports of the SDK. It won't actually work, any calls to OneSignal functions won't actually do anything, but at least it won't crash.
