### ISSUE TITLE
change notification large icon from REST Api 

### ISSUE THREAD

**Issue by mstf0ta-app** [OneSignal/react-native-onesignal#542]
hello 
i am using react native one signal
and i have a problem that i can change the notification large icon from the dashboard
but i am not find a way to send icon name from REST api 
i user this 

"large_icon":"large_icon"
but nothing change 

how can i solve that please ?

thanks
Best Regards

**Comment by Nightsd01** [comment]
There are a thousand possible reasons for this, and you haven't given enough information to really help you troubleshoot. In our issue template, we ask you to provide a lot of information (ie. what version of the react-native-onesignal SDK you are using, what version of react-native, and so on). 

I'll be closing this issue because you didn't provide this information, but if you can provide some more details I'll be happy to reopen + investigate.

1. Did your read our guide to android icons?
https://documentation.onesignal.com/docs/customize-notification-icons

2. Please post your react-native version, your react-native-onesignal version

3. Please post a ZIP of the actual icons you are using

**Comment by mstf0ta-app** [comment]
hello sir,

"react": "16.3.1",
"react-native": "^0.55.4",
"react-native-onesignal": "^3.2.4",

this is my versions
and i see the above link , and not clear how to send the icon from REST(or POSTMAN)
i make the icon size and place it in /java/res
and when i sent it`s name from dashboard it work
but i need to send it`s name from (POSTMAN) as a json object
this is my code in postman 

{
	"app_id": "---------",
"filters": [
  	{"field": "tag", "key": "test", "relation": "=", "value": "1253"}
  ],
  "data": {"Key_Not": "Trd10143"},
  "contents": {"en": " test"},
  "large_icon":"large_icon"

  }


thanks
Best Regards

**Comment by ShridharCodewave** [comment]
data: { actions: "action" },
  large_icon:"url",


I set the large icon in the REST api like I mentioned above and its working fine.
