### ISSUE TITLE
Android 8, 8.1 not working

### ISSUE THREAD

**Issue by tranvannhat** [OneSignal/react-native-onesignal#553]
Hi, i using react native onesignal for push notification but it's not woking on Android 8, 8.1 Please help me!

**Comment by Nightsd01** [comment]
Closing due to a total lack of details. We have an issue template for this reason.

**Comment by pacozaa** [comment]
@Nightsd01 I could say his issue is legit. Since I am facing the same problem too. `Onesignal` in my project works well with other version of android but with `8.0` and `8.1` are not working.

Given the context, I am using `"react-native-onesignal": "3.0.9"` then I try to use `"react-native-onesignal": "3.2.5"` and I debugged the error with `Android Studio` and it showed `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;`

That's all the context. If you need any more information please ask away, I need to solve this problem!

Thank you sir!

@tranvannhat Did you solve it?
