### ISSUE TITLE
App crash after open immediately?

### ISSUE THREAD

**Issue by pacozaa** [OneSignal/react-native-onesignal#558]
**Description:**

There is no error alert or anything the app just stopped after opened but I debug from Android studio and found this error.
```
 E/AndroidRuntime: FATAL EXCEPTION: main
  Process: app.udrinkidive.feed2us.com.udrinkidrivebeta, PID: 30554
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
 at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
```

**Environment**

`"react-native": "0.50.3"`
`using npm "react-native-onesignal": "^3.0.9",`
`'com.android.tools.build:gradle:3.0.0'`
`compileSdkVersion 26,
    buildToolsVersion "27.0.3"`

Is this have something to do with one-signal? because it is my only library that involve firebase. How to solve this?

**Comment by nilaybrahmbhatt** [comment]
same issue here.. any solution found?

**Comment by pacozaa** [comment]
@nilaybrahmbhatt Not yet. Not really. Stuck here for two weeks now.

**Comment by Nightsd01** [comment]
@pacozaa Unfortunately this is a common issue with Android & gradle in general. 

But it's also very well documented on Google

Here's some links you might find helpful. 

https://stackoverflow.com/questions/41322864/java-lang-noclassdeffounderror-failed-resolution-failed-resolution-of-lcom-goo
https://github.com/OneSignal/OneSignal-Android-SDK/issues/298

I'll be closing this issue since I do not see how it is related to our SDK. However I will reopen the issue if you can investigate further and provide some more details. Please try removing our SDK from your project and then re-run your app and let me know if the issue still occurs. If not, then please post some more information and I will be happy to reopen the issue and investigate

app/build.gradle
android/build.gradle
gradle-wrapper.properties

**Comment by connorbrassington** [comment]
@pacozaa Is this have something to do with one-signal? because it is my only library that involve firebase. How to solve this?

Double check you're implementing Firebase in your project, I get this issue when I forget to include Firebase Core. Check `android/app/build.gradle` includes the following.

```gradle
dependencies {
    ...

    implementation 'com.google.firebase:firebase-core:17.0.0'
}
```

https://firebase.google.com/docs/android/setup#add-sdks

If you haven't already you'll need a `google-services.json` configuration file for your project. You can follow this documentation on how to create one: https://firebase.google.com/docs/android/setup#add-config-file

This is a bit of a shot in the dark, nonetheless I hope it was helpful.
