### ISSUE TITLE
onReceived (notification) is called multiple times - Android

### ISSUE THREAD

**Issue by rbrezu** [OneSignal/react-native-onesignal#570]
I have seen #310 and i have a similar issue, but using singleInstance in my android manifest kills my app when going into background. I have also tried singleTop and singleTask but to no avail... for each background -> foreground action i add another receiver to the app. I am using react-native-navigation library too. Does anyone have any suggestions ?

**Comment by Nightsd01** [comment]
Without a stack trace, it's difficult to really help with this situation. I am assuming you're saying you're getting a crash...? But in general, it's pretty important to use `singleTop` or `singleTask` because otherwise, you could have multiple instances of OneSignal which can cause a lot of problems.

Can you please post a stack trace and more details?

Closing this issue because of a lack of details. If you can post more information (we have an issue template you can follow) I'll be happy to reopen & help to solve the issue.

**Comment by rbrezu** [comment]
Sorry for the late reply.

Had something to do with the version... was using 3.2.1.
Upgraded to 3.2.4 and now it's not happening anymore :)
