### ISSUE TITLE
Open push notification on Android

### ISSUE THREAD

**Issue by faustoct1** [OneSignal/react-native-onesignal#571]
@Nightsd01  When receive a push notification on Android and tap on it.. The notification takes too long to open on android. Let me know to add more details..

**Comment by Nightsd01** [comment]
@faustoct Closing this issue because of a lack of details.

We have an issue template asking for different types of information, it would be good to look at that. What do you mean when you say it "takes too long to open push notification"?

Please provide some more details and I'll be happy to reopen the issue and investigate.
