### ISSUE TITLE
Could not expand ZIP '\node_modules\react-native-onesignal\android\build\outputs\aar\react-native-onesignal-release.aar'

### ISSUE THREAD

**Issue by bashirpour** [OneSignal/react-native-onesignal#595]
>Execution failed for task ':app:prepareMelkanaReactNativeOnesignalUnspecifiedLibrary'.
> Could not expand ZIP 'MyProjects\node_modules\react-native-onesignal\android\build\outputs\aar\react-native-onesignal-release.aar'.

**Comment by Nightsd01** [comment]
Closing because of no additional information, ie. what version of the SDK you are using.

Try running `gradlew clean`. If that does not work, please post some more information about what version of the SDK you are using, what other plugins you're using, etc. and I'll be happy to reopen and help investigate the issue.
