### ISSUE TITLE
OneSignal.inFocusDisplaying(0) not working on iOS

### ISSUE THREAD

**Issue by juergengunz** [OneSignal/react-native-onesignal#627]
I am using the latest repo, still having issues with setting inFocusDisplaying to 0.
The notification is always appearing as if the app was in background.

if I set inFocusDisplaying to 1, it shows an inAppAlert but also the standard badge notification

I am sending notifications with custom sound, and I dont want it to play when the user is in the app when receiving a push notification

**Comment by Nightsd01** [comment]
Please add more details - are you talking about iOS or Android? 

When you say the "notification is always appearing as if the app was in background" what do you mean...? Can you share a screenshot?

Also, what do you mean by "standard badge notification"?

**Comment by juergengunz** [comment]
@Nightsd01 it says iOS in the title....

i mean the notification you receive in the notification center/lock screen

**Comment by Nightsd01** [comment]
Just to make sure we’re on the same page, you understand `inFocusDisplayType` only applies to when the app is actually open and in the foreground right?

When the app is in the background or closed, your app/our SDK has no control over how the system presents the notification. The only thing you can really do is use the Notifications Service Extension to cancel some notifications entirely from being displayed.

**Comment by juergengunz** [comment]
yes and this is exactly what is not working with OneSignal.inFocusDisplaying(0).

I set to OneSignal.inFocusDisplaying(0) and I expect to not receive any notification when the app is in the foreground but I still get the notification in the notification center.

If i set OneSignal.inFocusDisplaying(1) I get an inApp Alert and the notification in the notification center.

If i set OneSignal.inFocusDisplaying(2) I get the notification in the notification center.

**Comment by Nightsd01** [comment]
@juergengunz The `inFocusDisplayType` just controls how the notification gets **displayed** when the app is open. It doesn't actually cancel delivery of the notification. 

Unfortunately there is no easy/simple way to do this in iOS with our RN SDK either. 

Clearing the badge count in iOS also clears all received notifications, so I would suggest taking that approach. There are some npm react native packages that will clear the badge count in iOS

Closing because this isn't a bug with `inFocusDisplayType`
