### ISSUE TITLE
No profiles for 'com.myapp.ios.OneSignalNotificationServiceExtension' were found

### ISSUE THREAD

**Issue by valerybodak** [OneSignal/react-native-onesignal#646]
XCode 10.0. When I try to upload app to TestFlight I get the following error '**No profiles for 'com.myapp.ios.OneSignalNotificationServiceExtension' were found**'

![szb1t](https://user-images.githubusercontent.com/26433088/46465989-c52e3700-c7d2-11e8-86ec-8f7aa2d15f82.jpg)

Anyone help me? Thanks in advance.

**Comment by Nightsd01** [comment]
The error tells you what is wrong: your project is not configured with a provisioning profile for the extension service target.

Are you using the option to "Automatically manage signing"?

I'll be happy to help - but I'll be closing this issue since signing issues are not going to be a problem with our SDK.

**Comment by hpelitebook745G2** [comment]
@Nightsd01 I'm using "Automatically manage signing". How do I fix this?

**Comment by Nightsd01** [comment]
@hpelitebook745G2 can you post the error you’re seeing? If it’s exactly the same as the poster above, please look into the first error first, this is usually a permissions/teams issue.

**Comment by alexpchin** [comment]
Hi, what was the solution to this issue please? I am unable to build with Automatic Code Signing.

**Comment by xgenem** [comment]
Closed without solution 👎
