### ISSUE TITLE
OneSignal inFocusDisplaying(0) not working if it gets multiple notifications when openning.

### ISSUE THREAD

**Issue by kekkeme** [OneSignal/react-native-onesignal#696]
**Description:**

OneSignal inFocusDisplaying(0) it works fine. However, i think, there is some edge case . I have chat app. And user can send multiple message in close time. It happened on iOS 11 device. i did not make it happen on iOS 12 versions. 
Later i achieved same problem also iOS 12

**Environment**
"react-native-onesignal": "^3.2.8",
npm install react-native-onesignal
iOS 11, iOS 12

Steps to reproduce

Applications is fully closed it is not even background. And i get first notification and user clicks. I am handling this notification with web request for getting detail. However when app is openning in splash screen if it gets another notification it shows it as alert. After that it does not show any notification which is correct because i use inFocusDisplaying(0).

App.js
`componentWillMount() {
    OneSignal.init("xxxx id xxxx");
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
    OneSignal.configure();
    OneSignal.inFocusDisplaying(0);
  }`

**Comment by Nightsd01** [comment]
@kekkeme are you sure `setInFocusDisplaying(0)` is actually getting called while the splash screen is shown and the notification is seen? Are you saying it works normally unless the splash screen is being shown?

The React native runtime takes a bit of time to load before you can start executing JS instructions.

**Comment by kekkeme** [comment]
@Nightsd01 i think yes i am. I am configuring oneSignal inside of componentWillMount method of App.js. My fake splash screen is rendered inside render method of App.js, if it is not enough, what else i should do?

**Comment by Nightsd01** [comment]
@kekkeme This seems like quite an edge case, but if you want to handle it, there's not much we can do on the JavaScript side since it can take a while for the javascript engine to load.

If you need to handle this, I would suggest editing your AppDelegate and import our native iOS SDK, and call `OneSignal.inFocusDisplayType = OSNotificationDisplayTypeInAppNone;` inside of the `application:didFinishLaunchingWithOptions` method. This method will get called _very_ early on in the app lifecycle.
