### ISSUE TITLE
when app is closed notification sent  but how can i fetch post when notification received even the app closed?

### ISSUE THREAD

**Issue by srhtylmz19** [OneSignal/react-native-onesignal#706]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@srhtylmz19 Please add more details to your issue posts in the future since issues like this will be immediately closed. 

This is a _very common question_ and it has been asked here many times, please also try to use the search function (as our issue template makes super clear).

If the app is **running in the background**, you can set `content-available` to `1` to run the `opened` handler in the background in iOS.

If the app is terminated, neither iOS or Android will launch your app in the background. If you absolutely need to perform some logic when a notification is received, you can implement the Notification Extender Service in Android or the Notification Service Extension in iOS, but you would need to do this in Java or ObjC/Swift (native code) since it will not launch the React Native runtime.
