### ISSUE TITLE
Push notification button gets overridden when new notification arrives.

### ISSUE THREAD

**Issue by nateblog** [OneSignal/react-native-onesignal#707]
**Description:**

Push notification buttons gets overridden when new notification arrives like when I receive a notification that has a button saying **"Get Started**" and then the second notification arrives that has a button **"Upload Photo**", the first notification **"Get Started**" gets overridden and becomes "**Upload Photo**" as well.

I am expecting that the old unopened notifications should remain the same and should not inherent the payload of the new notifications.

**Environment**

React Native 0.54
React Native OneSignal "^3.2.11",
macOS Mojave version 10.14.2
Xcode version 10.1
Replicated the issue on version 11 and 12 iOS devices

**Steps to Reproduce Issue:**

1. Send two notifications with different button / buttons.
2. Check the first notification buttons / buttons after the second notification arrives.

**Comment by Nightsd01** [comment]
@nateblog Thank you for reporting this! It turns out this has been a bug in our SDK for quite a long time, I'm surprised it took this long for anyone to notice! 

It's a bug specifically with our native iOS SDK, and I've created a [pull request](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/481) to fix the problem.

**Comment by nateblog** [comment]
@Nightsd01 - Thank you so much, looking forward for the fix.
