### ISSUE TITLE
OneSignal doesn't detect any user (expo ejected)

### ISSUE THREAD

**Issue by AlexHrQ** [OneSignal/react-native-onesignal#724]
**Description:**

I've created app using expo and ejected it to ExpoKit. After that I added react-native-onesignal package and linked it using react-native link react-native-onesignal. After that I added code from https://documentation.onesignal.com/docs/react-native-sdk-setup#section-usage with correct appid. My app is running without errors but I keep getting "We haven't detected any subscribed users yet for this platform." on OneSignal dashboard.

**Environment**

    "expo": "^32.0.0",
    "expokit": "^32.0.6",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-onesignal": "^3.2.12"

**Steps to Reproduce Issue:**

1. expo init AppName (select next options => blank, managed)
2. expo eject (choose ExpoKit)
3. npm install react-native-onesignal --save
4. react-native link react-native-onesignal
5. create new app on onesignal dashboard
6. add code from link with valid appid
7. npm run start
8. click "Check Subscribed Users" button on website

**Comment by Nightsd01** [comment]
@HrytsynaAlex using `react-native link` is unnecessary if you install our SDK using Cocoapods, but that is probably not the issue here.

Please add more details, are you talking about iOS, or android, or both? 

There could be many possible issues here. Are you sure you followed every single step of our react-native SDK setup guide? Are you being prompted to allow Push Notification permission?

Please use `OneSignal.setLogLevel(6, 0)` and please post your logs for the first ~40 seconds of running your app (please upload the logs to somewhere like pastebin and just post the link here)

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by fxbayuanggara** [comment]
I have followed all instruction in https://documentation.onesignal.com/docs/react-native-sdk-setup#section-android-specific-instructions for Android, but the OneSignal still doesn't detect any user.

I am using Expo ejected, Expo SDK 33.

**Comment by devjva** [comment]
same problem, but I have nothing in the logs.
Expo SDK 40
