### ISSUE TITLE
Setting up OneSignalNotificationServiceExtension Signing Issues

### ISSUE THREAD

**Issue by lightninglu10** [OneSignal/react-native-onesignal#736]
**Description:**

Trying to setup OneSignalNotificationServiceExtension, but in XCode there are a multitude of issues.

Using Automatic Code Signing, it forces developer the iOS developer as the Code Signing Identity. This creates issues as we try to build the iOS app for distribution, we have mismatching signing identities. 

Trying to manually force the Code Signing to distribution gives us this error: 

```
OneSignalNotificationServiceExtension is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
```

**Environment**

   package: "react-native-onesignal": "^3.2.12",
added through Yarn, and Pod Installed

**Steps to Reproduce Issue:**

1. Try to setup Group App for NotificationServiceExtension

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@lightninglu10 the Extension service is an iOS concept - we did not invent it and it’s not part of our SDK. Because of this our SDK would not be causing these provisioning issues, so this is definitely not a bug/problem with our SDK. 

I would recommend setting up a provisioning profile for your Extension service for both dev and production, and then download the profiles and set the extension service target to use them. If you have two targets for dev vs. prod you will need two extension service targets as well.
