### ISSUE TITLE
-[UIApplication currentUserNotificationSettings] must be used from main thread only

### ISSUE THREAD

**Issue by LinusU** [OneSignal/react-native-onesignal#826]
**Description:**

With a recent version of React Native (e.g. 0.59) the functions are no longer called on the UI thread, and thus some calls needs to be explicitly dispatch to that thread.

We're consistently getting an error about the following line being called on a non-UI thread.

https://github.com/geektimecoil/react-native-onesignal/blob/9c83d4cc23b6862c0753b9d2af03b94ca68be453/ios/RCTOneSignal/RCTOneSignalEventEmitter.m#L126

I believe that the correct solution is to use `dispatch_sync` to populate `types` on the UI thread.

**Environment**
1. What version of the OneSignal React-Native SDK are you using? **3.2.14**
2. How did you add the SDK to your project? **npm**

**Steps to Reproduce Issue:**
  1. Create a new React Native 0.59 or newer project
  1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the iOS AppDelegate
  3. Attempt to receive a push notification
  4. Start app from Xcode
5. Notice error

**Comment by rgomezp** [comment]
@LinusU ,
Thanks for your detailed description. We will look into the issue, though this is the first report of it so I'm surprised no one else has asked. If you would be willing to fork the repo and test using `dispatch_sync` as you mentioned we would really appreciate it and would be able to resolve your issue faster. Otherwise, we appreciate your patience until we get back to this request.

**Comment by LinusU** [comment]
@rgomezp sorry for the late reply, I've been away on vacation 🍻 

I've tried out my suggested change locally and it indeed fixes the problem 👏 I've sent a pull request with the changes #832

**Comment by rgomezp** [comment]
Thanks for the PR. This issue should be resolved. Enjoy!
