### ISSUE TITLE
Why OneSignal the same steps as Firebase Cloud Messaging to configure APNs (iOS) ?

### ISSUE THREAD

**Issue by Steffi3rd** [OneSignal/react-native-onesignal#964]
Hello,

I know OneSignal and Firebase Cloud Messaging are different.

I’m on iOS, and already setup Firebase Cloud Messaging by importing **Auth Key. **
Notifications are received from Firebase Consoles, everything works great.

Now, I’m trying to setup OneSignal on another branch. 

And I see that OneSignal needs `.P12` instead `.Auth Key` to communicate with APNs.

Why? 
What’s the benefit? 

For this part, it looks like Firebase is simpler, but I just would like to know Why is different.

If someone has an answer for my knowledge... thank you! 🙏

**Comment by jkasten2** [comment]
@Steffi3rd A `.p12` used to be the only way to authenticate with Apple's APN service for most of its lifetime. Auth keys are simpler to generate and manage over `.p12` file so OneSignal does plan on supporting them in the future.

Since creating a [.p12 file manually takes such a large number of steps](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate#section-method-2-create-a-certificate-request-manually) OneSignal created a [.p12 provisionator tool](https://onesignal.com/provisionator) a while back to automate the process for you.
