### ISSUE TITLE
Question: Web support

### ISSUE THREAD

**Issue by hyochan** [OneSignal/react-native-onesignal#999]
**Description:**
React Native is moving fast to support web.
I've also wrote my experience in the [medium](https://medium.com/dooboolab/use-universal-expo-ios-android-web-to-create-your-app-5388d4594a9b).

As a `onesignal` lover, I want to know the future plan for supporting web env.

Where can I find the discussion related to this?

**Comment by rgomezp** [comment]
Howdy,
Thanks for showing interest in this feature. We currently have no plan to implement this. 

However, we are open to if there is enough interest. Please upvote this comment if you would like to see this supported.

Note: while this issue is closed, we will still consider the request and are tracking it internally. Thank you for your interest and support of OneSignal.

Enjoy!
